name: Whitesource
on: ["push"]
jobs:
  whitesource:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build whitesource
        run: docker build whitesource -t whitesource
      - name: run whitesource
        run: |
          docker run \
            -e WHITESOURCE_API_KEY=${{ secrets.WHITESOURCE_API_KEY }} \
            -e WHITESOURCE_USER_KEY=${{ secrets.WHITESOURCE_USER_KEY }} \
            -v $(pwd):/usr/src/app
            whitesource
          
          

